FROM python:3.12-slim

WORKDIR /app

# Dependências do sistema
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       git curl bash \
    && rm -rf /var/lib/apt/lists/*

# Dependências Python (DBT + pipeline)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Verifica instalação
RUN dbt --version
